replicaCount: 1

image:
  repository: mongo:latest

container:
  name: mongodb

service:
  type: NodePort
  port: 27017
  nodePort: 32000
  protocol: TCP

mongo:
  user: root
  password: changeit
  secretKeyRef:
    user: mongo-root-user
    password: mongo-root-password

ingress:
  enabled: false